# Generated by Django 4.1.3 on 2022-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produto', models.CharField(max_length=500)),
                ('ncm', models.CharField(max_length=500)),
                ('fecoep', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
